-- para facilitar testes
DROP TABLE RealizaEmprestimo CASCADE CONSTRAINTS;
DROP TABLE Avaliacao CASCADE CONSTRAINTS;
DROP TABLE Exemplar CASCADE CONSTRAINTS;
DROP TABLE Autor_Livro CASCADE CONSTRAINTS;
DROP TABLE Livro CASCADE CONSTRAINTS;
DROP TABLE Funcionario CASCADE CONSTRAINTS;
DROP TABLE Matricula CASCADE CONSTRAINTS;
DROP TABLE Aluno CASCADE CONSTRAINTS;
DROP TABLE Telefone CASCADE CONSTRAINTS;
DROP TABLE Pessoa CASCADE CONSTRAINTS;
DROP TABLE Endereco CASCADE CONSTRAINTS;

DROP SEQUENCE seq_pessoa;
DROP SEQUENCE seq_telefone;
DROP SEQUENCE seq_funcionario;
